name: Update gist

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */8 * * *"   # Runs every 8 hours
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
      - uses: actions/checkout@master
      
      - name: "Setup Deno"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: "Update gist"
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASEID: ${{ secrets.NOTION_DATABASEID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: deno run --allow-net --allow-env index.ts
