name: Update gist

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */8 * * *"   # Runs every 8 hours
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - name: update-gist
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASEID: ${{ secrets.NOTION_DATABASEID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: npm start